### ISSUE TITLE
Ветвь `ci-dev-2023.09.27`

### ISSUE THREAD

**Issue by p5-vbnekit** [Zavyalov-Yu/gpredictTestWork#1]
Для удобства дальнейшей разработки необходимо создать ветку в репозитории с именем `ci-dev-2023.09.27`.
Смотрите раздел `3. Git Branching` в [документации по git](https://git-scm.com/book/en/v2).

**Comment by Zavyalov-Yu** [comment]
Создана ветка "ci-dev-2023.09.27".

**Comment by p5-vbnekit** [comment]
Отлично!
Теперь нужно слить все изменения в один коммит в ветку `master` (выполнить `git merge --squash`).
Данная операция агрегирует все осмысленные действия в одну заплатку, которую потом проще будет передать другим разрабочикам (например запросить слияние в upstream, а так же если потребуется выполнить `git rebase`).
Таким образом ваша основная ветвь `master` в форке будет отличаться от `upstream` всего на 1 коммит, что существенно упростит процесс "code review" для других разработчиков.
Полная история изменений по прежнему будет сохранена в ветке `ci-dev-2023.09.27`.

**Comment by Zavyalov-Yu** [comment]
Вроде готово.
